language: python

python:
  - 2.7

services:
  - postgresql

install:
  - pip install -r requirements.txt
  - pip install codecov

script:
  #- python backup.py
  - coverage run backup.py

after_success:
  - codecov
